### ISSUE TITLE
安装了依赖还是启动报错

### ISSUE THREAD

**Issue by narwhrl** [CCYellowStar/zhenxun_plugin_pica#2]
其实我没太懂`进入真寻虚拟环境`后再安装依赖是什么意思...
我是在服务器Ubuntu环境上部署的，因为用的是手动部署，
所以就cd到插件目录后`poetry run pip install -r requirements.txt`了，
发现报错之后我还直接`pip install -r requirements.txt`了一次，仍然报错TAT

具体日志：
```
02-12 16:57:57 [ERROR] nonebot | Failed to import "zhenxun_plugin_pica"
Traceback (most recent call last):
  File "/home/zhenxun_bot/bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zhenxun_bot/plugins/zhenxun_plugin_pica/__init__.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by PackageInstaller** [comment]
具体步骤是这样
在真寻的主目录下执行poetry shell
然后cd进插件这个目录
最后pip install -r requirements.txt

**Comment by PackageInstaller** [comment]
![image](https://user-images.githubusercontent.com/80018096/218378056-a45b5f78-e30a-4183-8677-8b18c3e5c80d.png)
我这是已经安装过的，但是大概差不多

**Comment by narwhrl** [comment]
> 我这是已经安装过的，但是大概差不多

执行结果也显示我已经安装了欸，但是还是和上面一样的报错
```
(zhenxun-bot-py3.9) root@racknerd-4d5a30:/home/zhenxun_bot/plugins# cd zhenxun_plugin_pica
(zhenxun-bot-py3.9) root@racknerd-4d5a30:/home/zhenxun_bot/plugins/zhenxun_plugin_pica# pip install -r requirements.txt
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: ujson in /root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (5.6.0)
Requirement already satisfied: python-levenshtein in /root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.20.9)
Requirement already satisfied: OpenCC in /root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.1.6)
Requirement already satisfied: fuzzywuzzy in /root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.18.0)
Requirement already satisfied: Levenshtein==0.20.9 in /root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages (from python-levenshtein->-r requirements.txt (line 2)) (0.20.9)
Requirement already satisfied: rapidfuzz<3.0.0,>=2.3.0 in /root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages (from Levenshtein==0.20.9->python-levenshtein->-r requirements.txt (line 2)) (2.13.7)

```

**Comment by PackageInstaller** [comment]
要不你放extensive_plugin文件夹再试试？

**Comment by narwhrl** [comment]
> 要不你把插件移动到extensive_plugin文件夹再重新执行一遍所有操作试试？

依然报错QAQ...
日志：

### 安装依赖
```
(zhenxun-bot-py3.9) root@racknerd-4d5a30:/home/zhenxun_bot# cd /home/zhenxun_bot/extensive_plugin/zhenxun_plugin_pica/
(zhenxun-bot-py3.9) root@racknerd-4d5a30:/home/zhenxun_bot/extensive_plugin/zhenxun_plugin_pica# pip install -r requirements.txt
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: ujson in /root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (5.6.0)
Requirement already satisfied: python-levenshtein in /root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.20.9)
Requirement already satisfied: OpenCC in /root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.1.6)
Requirement already satisfied: fuzzywuzzy in /root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.18.0)
Requirement already satisfied: Levenshtein==0.20.9 in /root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages (from python-levenshtein->-r requirements.txt (line 2)) (0.20.9)
Requirement already satisfied: rapidfuzz<3.0.0,>=2.3.0 in /root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages (from Levenshtein==0.20.9->python-levenshtein->-r requirements.txt (line 2)) (2.13.7)
(zhenxun-bot-py3.9) root@racknerd-4d5a30:/home/zhenxun_bot/extensive_plugin/zhenxun_plugin_pica# cd /home/zhenxun_bot/
(zhenxun-bot-py3.9) root@racknerd-4d5a30:/home/zhenxun_bot# python3 bot.py
02-13 05:36:40 [SUCCESS] nonebot | NoneBot is initializing...
```

### 报错
```
02-13 05:36:50 [ERROR] nonebot | Failed to import "zhenxun_plugin_pica"
Traceback (most recent call last):
  File "/home/zhenxun_bot/bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zhenxun_bot/extensive_plugin/zhenxun_plugin_pica/__init__.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by PackageInstaller** [comment]
那我就不知道了，等插件作者或是其他大佬回复吧
![image](https://user-images.githubusercontent.com/80018096/218379644-8eabf018-f216-4edd-b66f-4e1397ceb5b2.png)

**Comment by narwhrl** [comment]
> 那我就不知道了，等插件作者或是其他大佬回复吧 

hhh既然报错显示缺少requests模块我就自己用`pip install requests`手动安装了一下
没想到还真的有效果了！
我倒回去看看`requirement.txt`，里面真的没有这个模块，可能作者在制作的时候并没有考虑到这个模块未安装的情况？
不过还是很感谢老哥帮忙了！

### 解决方案：
看报错日志缺少什么模块就用`pip install <模块名> `进行安装

**Comment by CCYellowStar** [comment]
emmm，我记得真寻装完不是带这个模块的吗

**Comment by PackageInstaller** [comment]
我也记得是自带这个，可能是装的时候没装全

**Comment by narwhrl** [comment]
> emmm，我记得真寻装完不是带这个模块的吗

我也不知道呀... 我是跟着手动部署流程一步一步装的，也许是没安装上=w=

**Comment by CCYellowStar** [comment]
好像是我的问题，这个requests在真寻这个异步机器人是用不到的，我移植的那个机器人用的是requests然后我改了后依赖请求没删
